apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-creds-operator-secrets
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: {{.Values.env}}/eks-{{.Values.env}}/registry-creds-operator/registry-creds-operator-secrets
        decodingStrategy: None
        metadataPolicy: None
  refreshInterval: 60s
  secretStoreRef:
    name: registry-creds-operator
    kind: SecretStore
  target:
    name: registry-creds-operator-secrets
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: registry-creds-operator
spec:
  provider:
    aws:
      service: SecretsManager
      auth:
        jwt:
          serviceAccountRef:
            name: registry-creds-operator
      region: eu-west-1
  refreshInterval: 60
  retrySettings:
    maxRetries: 5
    retryInterval: 60s