apiVersion: ops.alexellis.io/v1
kind: ClusterPullSecret
metadata:
  name: dockerhub
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  secretRef:
    name: registry-creds-operator-secrets
    namespace: registry-creds-operator
