apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-creds-operator
  annotations:
{{- if eq .Values.env "prod" }}
    eks.amazonaws.com/role-arn: arn:aws:iam::706922411989:role/registry-creds-operator
{{- else }}
    eks.amazonaws.com/role-arn: arn:aws:iam::007554613773:role/registry-creds-operator
{{- end }}
